<?php

use yii\db\Migration;

/**
 * Class m231102_180814_add_rows
 */
class m231108_231503_add_rows extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $rows = [
            [
                "nome"=> "Eloá Andrea Duarte",
                "idade"=> 33,
                "cpf"=> "747.887.537-82",
                "rg"=> "41.281.881-4",
                "data_nasc"=> "09/09/1990",
                "sexo"=> "Feminino",
                "signo"=> "Virgem",
                "mae"=> "Emanuelly Milena Caroline",
                "pai"=> "Daniel Hugo Arthur Duarte",
                "email"=> "eloa_andrea_duarte@slb.com",
                "senha"=> "kcwJeRWOX7",
                "cep"=> 68742710,
                "endereco"=> "Rua Belém",
                "numero"=> 610,
                "bairro"=> "Nova Olinda",
                "cidade"=> "Castanhal",
                "estado"=> "PA",
                "telefone_fixo"=> "(91) 2617-5678",
                "celular"=> "(91) 98690-0978",
                "altura"=> "1,66",
                "peso"=> 46,
                "tipo_sanguineo"=> "AB+",
                "cor"=> "preto"
            ],
            [
                "nome"=> "Pietro Antonio Melo",
                "idade"=> 18,
                "cpf"=> "804.527.382-88",
                "rg"=> "14.528.840-7",
                "data_nasc"=> "18/07/2005",
                "sexo"=> "Masculino",
                "signo"=> "Câncer",
                "mae"=> "Nicole Larissa",
                "pai"=> "Márcio Osvaldo Melo",
                "email"=> "pietro_melo@imail.com",
                "senha"=> "3twjmfistm",
                "cep"=> 40750326,
                "endereco"=> "Rua Vitória",
                "numero"=> 508,
                "bairro"=> "Coutos",
                "cidade"=> "Salvador",
                "estado"=> "BA",
                "telefone_fixo"=> "(71) 3736-6591",
                "celular"=> "(71) 99387-1342",
                "altura"=> "1,78",
                "peso"=> 88,
                "tipo_sanguineo"=> "A-",
                "cor"=> "azul"
            ],
            [
                "nome"=> "Ryan Juan Teixeira",
                "idade"=> 79,
                "cpf"=> "996.754.135-06",
                "rg"=> "26.540.513-0",
                "data_nasc"=> "06/05/1944",
                "sexo"=> "Masculino",
                "signo"=> "Touro",
                "mae"=> "Fabiana Evelyn Yasmin",
                "pai"=> "Jorge Theo Teixeira",
                "email"=> "ryan_juan_teixeira@guiandotelecom.com.br",
                "senha"=> "Yo2QzpjdxX",
                "cep"=> 68908271,
                "endereco"=> "Passagem Rio Grande do Norte",
                "numero"=> 160,
                "bairro"=> "Pacoval",
                "cidade"=> "Macapá",
                "estado"=> "AP",
                "telefone_fixo"=> "(96) 3908-4443",
                "celular"=> "(96) 99576-1402",
                "altura"=> "1,88",
                "peso"=> 110,
                "tipo_sanguineo"=> "O-",
                "cor"=> "vermelho"
            ],
            [
                "nome"=> "Antonella Luzia Bárbara Lima",
                "idade"=> 56,
                "cpf"=> "087.719.535-82",
                "rg"=> "43.448.760-0",
                "data_nasc"=> "26/02/1967",
                "sexo"=> "Feminino",
                "signo"=> "Peixes",
                "mae"=> "Julia Nair Lorena",
                "pai"=> "Jorge Jorge Victor Lima",
                "email"=> "antonella_luzia_lima@oticascarol.com.br",
                "senha"=> "SNAlXw2nmk",
                "cep"=> 49072370,
                "endereco"=> "Travessa João Benevides Marques",
                "numero"=> 643,
                "bairro"=> "Dezoito do Forte",
                "cidade"=> "Aracaju",
                "estado"=> "SE",
                "telefone_fixo"=> "(79) 2595-2672",
                "celular"=> "(79) 98490-9712",
                "altura"=> "1,57",
                "peso"=> 49,
                "tipo_sanguineo"=> "A-",
                "cor"=> "roxo"
            ],
            [
                "nome"=> "Mariane Benedita Campos",
                "idade"=> 72,
                "cpf"=> "497.208.969-57",
                "rg"=> "25.410.859-3",
                "data_nasc"=> "01/11/1951",
                "sexo"=> "Feminino",
                "signo"=> "Escorpião",
                "mae"=> "Rayssa Josefa Simone",
                "pai"=> "Carlos Eduardo Elias Vinicius Campos",
                "email"=> "mariane_benedita_campos@ssala.com.br",
                "senha"=> "aPywmwjBTK",
                "cep"=> 40484230,
                "endereco"=> "Avenida da Horta",
                "numero"=> 557,
                "bairro"=> "Alto do Cabrito",
                "cidade"=> "Salvador",
                "estado"=> "BA",
                "telefone_fixo"=> "(71) 2649-6232",
                "celular"=> "(71) 99342-5228",
                "altura"=> "1,61",
                "peso"=> 56,
                "tipo_sanguineo"=> "B+",
                "cor"=> "roxo"
            ],
            [
                "nome"=> "Arthur César Corte Real",
                "idade"=> 54,
                "cpf"=> "021.974.063-10",
                "rg"=> "21.261.774-6",
                "data_nasc"=> "20/08/1969",
                "sexo"=> "Masculino",
                "signo"=> "Leão",
                "mae"=> "Sophia Nicole",
                "pai"=> "Felipe Mateus Bryan Corte Real",
                "email"=> "arthur.cesar.cortereal@jglima.com.br",
                "senha"=> "OHh6qbZ91Y",
                "cep"=> 66070040,
                "endereco"=> "Alameda Santo Agostinho",
                "numero"=> 442,
                "bairro"=> "Terra Firme",
                "cidade"=> "Belém",
                "estado"=> "PA",
                "telefone_fixo"=> "(91) 3510-5128",
                "celular"=> "(91) 99273-2420",
                "altura"=> "1,60",
                "peso"=> 73,
                "tipo_sanguineo"=> "O+",
                "cor"=> "amarelo"
            ],
            [
                "nome"=> "Vitor Enrico Martins",
                "idade"=> 25,
                "cpf"=> "341.548.327-43",
                "rg"=> "33.856.856-6",
                "data_nasc"=> "25/09/1998",
                "sexo"=> "Masculino",
                "signo"=> "Libra",
                "mae"=> "Tatiane Isadora",
                "pai"=> "Fernando Ian Anthony Martins",
                "email"=> "vitor_enrico_martins@iaru.com",
                "senha"=> "Ut02ghDgZI",
                "cep"=> 59155570,
                "endereco"=> "Rua Salvador Gurgel do Amaral",
                "numero"=> 390,
                "bairro"=> "Liberdade",
                "cidade"=> "Parnamirim",
                "estado"=> "RN",
                "telefone_fixo"=> "(84) 3848-7877",
                "celular"=> "(84) 99698-1182",
                "altura"=> "1,97",
                "peso"=> 84,
                "tipo_sanguineo"=> "B-",
                "cor"=> "roxo"
            ],
            [
                "nome"=> "Bryan Daniel Kaique Monteiro",
                "idade"=> 69,
                "cpf"=> "114.429.586-69",
                "rg"=> "23.137.199-8",
                "data_nasc"=> "03/08/1954",
                "sexo"=> "Masculino",
                "signo"=> "Leão",
                "mae"=> "Maitê Rayssa Sandra",
                "pai"=> "Sérgio Cauã Monteiro",
                "email"=> "bryan-monteiro74@malosti.com.br",
                "senha"=> "mlcSliG4Mz",
                "cep"=> 90050310,
                "endereco"=> "Rua Luiz Afonso",
                "numero"=> 682,
                "bairro"=> "Cidade Baixa",
                "cidade"=> "Porto Alegre",
                "estado"=> "RS",
                "telefone_fixo"=> "(51) 3967-3179",
                "celular"=> "(51) 99816-2815",
                "altura"=> "1,66",
                "peso"=> 64,
                "tipo_sanguineo"=> "A-",
                "cor"=> "preto"
            ],
            [
                "nome"=> "Aparecida Lívia da Rocha",
                "idade"=> 59,
                "cpf"=> "278.865.047-71",
                "rg"=> "50.284.275-1",
                "data_nasc"=> "15/08/1964",
                "sexo"=> "Feminino",
                "signo"=> "Leão",
                "mae"=> "Maitê Luana",
                "pai"=> "Márcio Cauê Kauê da Rocha",
                "email"=> "aparecida_darocha@bol.co.br",
                "senha"=> "o8I1o9rxYu",
                "cep"=> 69915491,
                "endereco"=> "Alameda Bolivia",
                "numero"=> 249,
                "bairro"=> "Jardim Europa",
                "cidade"=> "Rio Branco",
                "estado"=> "AC",
                "telefone_fixo"=> "(68) 3941-8353",
                "celular"=> "(68) 98267-6150",
                "altura"=> "1,77",
                "peso"=> 58,
                "tipo_sanguineo"=> "O-",
                "cor"=> "verde"
            ],
            [
                "nome"=> "Luís Yuri Brito",
                "idade"=> 40,
                "cpf"=> "849.414.292-57",
                "rg"=> "15.194.759-4",
                "data_nasc"=> "04/04/1983",
                "sexo"=> "Masculino",
                "signo"=> "Áries",
                "mae"=> "Allana Isabelle",
                "pai"=> "Erick Breno Theo Brito",
                "email"=> "luis_yuri_brito@custodes.com.br",
                "senha"=> "WXh3KXIGAC",
                "cep"=> 76813501,
                "endereco"=> "Rua Pedro Cabral",
                "numero"=> 565,
                "bairro"=> "Mariana",
                "cidade"=> "Porto Velho",
                "estado"=> "RO",
                "telefone_fixo"=> "(69) 2529-5297",
                "celular"=> "(69) 98879-3781",
                "altura"=> "1,98",
                "peso"=> 87,
                "tipo_sanguineo"=> "O-",
                "cor"=> "laranja"
            ],
            [
                "nome"=> "Danilo Augusto Luan Aragão",
                "idade"=> 65,
                "cpf"=> "472.532.251-20",
                "rg"=> "26.468.927-6",
                "data_nasc"=> "13/09/1958",
                "sexo"=> "Masculino",
                "signo"=> "Virgem",
                "mae"=> "Hadassa Rayssa",
                "pai"=> "Danilo Iago Aragão",
                "email"=> "danilo.augusto.aragao@mcpsolucoesgraficas.com.br",
                "senha"=> "wup6qoDKms",
                "cep"=> 63505100,
                "endereco"=> "Rua Getúlio Vargas",
                "numero"=> 260,
                "bairro"=> "Esplanada II",
                "cidade"=> "Iguatu",
                "estado"=> "CE",
                "telefone_fixo"=> "(88) 3566-6568",
                "celular"=> "(88) 99352-1506",
                "altura"=> "1,94",
                "peso"=> 79,
                "tipo_sanguineo"=> "AB+",
                "cor"=> "vermelho"
            ],
            [
                "nome"=> "Louise Larissa Cavalcanti",
                "idade"=> 51,
                "cpf"=> "688.871.267-20",
                "rg"=> "46.734.322-6",
                "data_nasc"=> "19/06/1972",
                "sexo"=> "Feminino",
                "signo"=> "Gêmeos",
                "mae"=> "Francisca Isadora",
                "pai"=> "Samuel Vicente Cavalcanti",
                "email"=> "louiselarissacavalcanti@sefaz.am.gov.br",
                "senha"=> "Y9iSLhGSyM",
                "cep"=> 27253522,
                "endereco"=> "Rua Ayrton Senna",
                "numero"=> 946,
                "bairro"=> "São Geraldo",
                "cidade"=> "Volta Redonda",
                "estado"=> "RJ",
                "telefone_fixo"=> "(24) 2843-3595",
                "celular"=> "(24) 99379-6376",
                "altura"=> "1,81",
                "peso"=> 45,
                "tipo_sanguineo"=> "A-",
                "cor"=> "amarelo"
            ],
            [
                "nome"=> "Gabriel Manuel Porto",
                "idade"=> 22,
                "cpf"=> "446.269.854-16",
                "rg"=> "35.135.676-9",
                "data_nasc"=> "24/07/2001",
                "sexo"=> "Masculino",
                "signo"=> "Leão",
                "mae"=> "Jaqueline Caroline Lúcia",
                "pai"=> "Vicente Geraldo Daniel Porto",
                "email"=> "gabrielmanuelporto@ft.unicamp.br",
                "senha"=> "ofGzX2z6ZJ",
                "cep"=> 78233970,
                "endereco"=> "Rua Principal, s/n",
                "numero"=> 475,
                "bairro"=> "Getúlio Vargas",
                "cidade"=> "Cáceres",
                "estado"=> "MT",
                "telefone_fixo"=> "(65) 2958-7474",
                "celular"=> "(65) 98133-8217",
                "altura"=> "1,82",
                "peso"=> 92,
                "tipo_sanguineo"=> "B+",
                "cor"=> "preto"
            ],
            [
                "nome"=> "Alessandra Rosa Clara Vieira",
                "idade"=> 61,
                "cpf"=> "684.775.180-09",
                "rg"=> "28.013.949-4",
                "data_nasc"=> "01/11/1962",
                "sexo"=> "Feminino",
                "signo"=> "Escorpião",
                "mae"=> "Brenda Josefa",
                "pai"=> "Anthony Nathan Juan Vieira",
                "email"=> "alessandra_vieira@citadini.imb.br",
                "senha"=> "09yaRL1xg1",
                "cep"=> 49040460,
                "endereco"=> "Avenida Paulo VI",
                "numero"=> 469,
                "bairro"=> "Inácio Barbosa",
                "cidade"=> "Aracaju",
                "estado"=> "SE",
                "telefone_fixo"=> "(79) 2877-1530",
                "celular"=> "(79) 99526-3984",
                "altura"=> "1,63",
                "peso"=> 84,
                "tipo_sanguineo"=> "O+",
                "cor"=> "verde"
            ],
            [
                "nome"=> "Guilherme Enzo Yuri Costa",
                "idade"=> 44,
                "cpf"=> "402.182.396-45",
                "rg"=> "17.139.157-3",
                "data_nasc"=> "04/04/1979",
                "sexo"=> "Masculino",
                "signo"=> "Áries",
                "mae"=> "Emanuelly Jaqueline Luiza",
                "pai"=> "Martin Levi Costa",
                "email"=> "guilherme_costa@rebecacometerra.com.br",
                "senha"=> "ZjZLqFTGFr",
                "cep"=> 76821468,
                "endereco"=> "Rua Professor Cervanes Monteiro",
                "numero"=> 129,
                "bairro"=> "Rio Madeira",
                "cidade"=> "Porto Velho",
                "estado"=> "RO",
                "telefone_fixo"=> "(69) 2876-9090",
                "celular"=> "(69) 99304-0882",
                "altura"=> "1,93",
                "peso"=> 84,
                "tipo_sanguineo"=> "B-",
                "cor"=> "laranja"
            ],
            [
                "nome"=> "Manoel Breno Ribeiro",
                "idade"=> 34,
                "cpf"=> "702.224.216-06",
                "rg"=> "13.495.867-6",
                "data_nasc"=> "03/10/1989",
                "sexo"=> "Masculino",
                "signo"=> "Libra",
                "mae"=> "Beatriz Ana",
                "pai"=> "Henry Nicolas Ruan Ribeiro",
                "email"=> "manoel_breno_ribeiro@powerblade.com.br",
                "senha"=> "8tpbD525xN",
                "cep"=> 17018160,
                "endereco"=> "Rua Pio Bigella Curiel",
                "numero"=> 739,
                "bairro"=> "Samambaia Parque Residencial",
                "cidade"=> "Bauru",
                "estado"=> "SP",
                "telefone_fixo"=> "(14) 2911-3971",
                "celular"=> "(14) 98478-1294",
                "altura"=> "1,78",
                "peso"=> 63,
                "tipo_sanguineo"=> "B+",
                "cor"=> "roxo"
            ],
            [
                "nome"=> "Gabriel Erick Kevin Viana",
                "idade"=> 64,
                "cpf"=> "681.851.834-65",
                "rg"=> "37.676.178-7",
                "data_nasc"=> "06/02/1959",
                "sexo"=> "Masculino",
                "signo"=> "Aquário",
                "mae"=> "Débora Emilly Tatiane",
                "pai"=> "Filipe Nathan Viana",
                "email"=> "gabriel.erick.viana@prohaska.com.br",
                "senha"=> "uQ8wJFPl46",
                "cep"=> 77490970,
                "endereco"=> "Rua 22 de Maio 272",
                "numero"=> 986,
                "bairro"=> "Setor Central",
                "cidade"=> "Cristalândia",
                "estado"=> "TO",
                "telefone_fixo"=> "(63) 2887-7225",
                "celular"=> "(63) 99648-2179",
                "altura"=> "1,98",
                "peso"=> 71,
                "tipo_sanguineo"=> "O-",
                "cor"=> "verde"
            ],
            [
                "nome"=> "Emanuelly Stella da Cruz",
                "idade"=> 48,
                "cpf"=> "306.724.621-76",
                "rg"=> "18.650.487-1",
                "data_nasc"=> "08/09/1975",
                "sexo"=> "Feminino",
                "signo"=> "Virgem",
                "mae"=> "Betina Fabiana Luzia",
                "pai"=> "Iago Manuel Leandro da Cruz",
                "email"=> "emanuelly-dacruz78@ozsurfing.com.br",
                "senha"=> "Sc39BAkBOp",
                "cep"=> 77410080,
                "endereco"=> "Avenida Rio Grande do Norte",
                "numero"=> 356,
                "bairro"=> "Setor Central",
                "cidade"=> "Gurupi",
                "estado"=> "TO",
                "telefone_fixo"=> "(63) 2682-2265",
                "celular"=> "(63) 99369-6826",
                "altura"=> "1,61",
                "peso"=> 51,
                "tipo_sanguineo"=> "AB-",
                "cor"=> "amarelo"
            ],
            [
                "nome"=> "Gael Nelson Pedro Henrique Silva",
                "idade"=> 46,
                "cpf"=> "645.017.126-00",
                "rg"=> "48.524.621-1",
                "data_nasc"=> "02/09/1977",
                "sexo"=> "Masculino",
                "signo"=> "Virgem",
                "mae"=> "Alessandra Marcela",
                "pai"=> "Manuel Luís Silva",
                "email"=> "gael_silva@texfuse.com.br",
                "senha"=> "p2kxHhjr4D",
                "cep"=> 83065574,
                "endereco"=> "Rua Mário Saade",
                "numero"=> 884,
                "bairro"=> "Rio Pequeno",
                "cidade"=> "São José dos Pinhais",
                "estado"=> "PR",
                "telefone_fixo"=> "(41) 2839-8238",
                "celular"=> "(41) 99511-1019",
                "altura"=> "1,96",
                "peso"=> 76,
                "tipo_sanguineo"=> "O+",
                "cor"=> "azul"
            ],
            [
                "nome"=> "Guilherme Raul Nogueira",
                "idade"=> 42,
                "cpf"=> "563.082.467-86",
                "rg"=> "13.304.834-2",
                "data_nasc"=> "27/05/1981",
                "sexo"=> "Masculino",
                "signo"=> "Gêmeos",
                "mae"=> "Emily Emily Emanuelly",
                "pai"=> "César Paulo Giovanni Nogueira",
                "email"=> "guilherme.raul.nogueira@iedi.com.br",
                "senha"=> "O3qWw3jMw2",
                "cep"=> 38705308,
                "endereco"=> "Rua Y",
                "numero"=> 443,
                "bairro"=> "Sebastião Amorim",
                "cidade"=> "Patos de Minas",
                "estado"=> "MG",
                "telefone_fixo"=> "(34) 3946-7683",
                "celular"=> "(34) 98959-5220",
                "altura"=> "1,61",
                "peso"=> 94,
                "tipo_sanguineo"=> "B-",
                "cor"=> "vermelho"
            ],
            [
                "nome"=> "Rafael Enzo Carvalho",
                "idade"=> 56,
                "cpf"=> "047.412.643-94",
                "rg"=> "49.248.441-7",
                "data_nasc"=> "02/02/1967",
                "sexo"=> "Masculino",
                "signo"=> "Aquário",
                "mae"=> "Louise Laura Clarice",
                "pai"=> "Jorge Leandro Carvalho",
                "email"=> "rafael-carvalho86@progetamos.com.br",
                "senha"=> "b0DMyZ0Q7n",
                "cep"=> 69911782,
                "endereco"=> "Rua 25 de Fevereiro",
                "numero"=> 346,
                "bairro"=> "Boa União",
                "cidade"=> "Rio Branco",
                "estado"=> "AC",
                "telefone_fixo"=> "(68) 2624-7669",
                "celular"=> "(68) 98518-3057",
                "altura"=> "1,80",
                "peso"=> 78,
                "tipo_sanguineo"=> "B+",
                "cor"=> "amarelo"
            ],
            [
                "nome"=> "Letícia Gabrielly Liz Silveira",
                "idade"=> 59,
                "cpf"=> "439.208.543-06",
                "rg"=> "25.945.066-2",
                "data_nasc"=> "07/09/1964",
                "sexo"=> "Feminino",
                "signo"=> "Virgem",
                "mae"=> "Luna Márcia",
                "pai"=> "Giovanni Lucca Vicente Silveira",
                "email"=> "leticia_silveira@bitco.cc",
                "senha"=> "9QFBamZdyT",
                "cep"=> 77425090,
                "endereco"=> "Rua S-013",
                "numero"=> 696,
                "bairro"=> "Parque Sol Nascente",
                "cidade"=> "Gurupi",
                "estado"=> "TO",
                "telefone_fixo"=> "(63) 2905-1451",
                "celular"=> "(63) 98574-1739",
                "altura"=> "1,63",
                "peso"=> 51,
                "tipo_sanguineo"=> "B+",
                "cor"=> "preto"
            ],
            [
                "nome"=> "Eduarda Clarice Sara de Paula",
                "idade"=> 50,
                "cpf"=> "006.483.231-70",
                "rg"=> "10.979.110-1",
                "data_nasc"=> "10/05/1973",
                "sexo"=> "Feminino",
                "signo"=> "Touro",
                "mae"=> "Marli Louise",
                "pai"=> "Sérgio Julio de Paula",
                "email"=> "eduarda_clarice_depaula@foar.unesp.br",
                "senha"=> "sDLaL5S6A6",
                "cep"=> 89026420,
                "endereco"=> "Rua Ourinhos",
                "numero"=> 429,
                "bairro"=> "Progresso",
                "cidade"=> "Blumenau",
                "estado"=> "SC",
                "telefone_fixo"=> "(47) 3704-5571",
                "celular"=> "(47) 98461-8892",
                "altura"=> "1,59",
                "peso"=> 45,
                "tipo_sanguineo"=> "AB-",
                "cor"=> "vermelho"
            ],
            [
                "nome"=> "André Luan da Rosa",
                "idade"=> 26,
                "cpf"=> "087.017.881-40",
                "rg"=> "25.260.970-0",
                "data_nasc"=> "15/04/1997",
                "sexo"=> "Masculino",
                "signo"=> "Áries",
                "mae"=> "Camila Isabel Alícia",
                "pai"=> "Raul André Kevin da Rosa",
                "email"=> "andre_darosa@policiamilitar.sp.gov.br",
                "senha"=> "5NEixWLpcx",
                "cep"=> 68908036,
                "endereco"=> "Rua Aracaju",
                "numero"=> 132,
                "bairro"=> "Infraero",
                "cidade"=> "Macapá",
                "estado"=> "AP",
                "telefone_fixo"=> "(96) 3726-3107",
                "celular"=> "(96) 98427-4803",
                "altura"=> "1,92",
                "peso"=> 76,
                "tipo_sanguineo"=> "A-",
                "cor"=> "vermelho"
            ],
            [
                "nome"=> "Victor Lorenzo da Mata",
                "idade"=> 37,
                "cpf"=> "203.165.534-50",
                "rg"=> "21.120.141-8",
                "data_nasc"=> "03/02/1986",
                "sexo"=> "Masculino",
                "signo"=> "Aquário",
                "mae"=> "Eliane Bruna",
                "pai"=> "Thomas Davi Vinicius da Mata",
                "email"=> "victor.lorenzo.damata@eternalam.com.br",
                "senha"=> "gDb8Cccjb1",
                "cep"=> 89253540,
                "endereco"=> "Rua Tereza Aigner Hruschka",
                "numero"=> 699,
                "bairro"=> "São Luís",
                "cidade"=> "Jaraguá do Sul",
                "estado"=> "SC",
                "telefone_fixo"=> "(47) 3813-2008",
                "celular"=> "(47) 98180-5201",
                "altura"=> "1,82",
                "peso"=> 52,
                "tipo_sanguineo"=> "B+",
                "cor"=> "amarelo"
            ],
            [
                "nome"=> "Betina Beatriz Caroline da Conceição",
                "idade"=> 72,
                "cpf"=> "213.074.360-99",
                "rg"=> "21.769.239-4",
                "data_nasc"=> "14/07/1951",
                "sexo"=> "Feminino",
                "signo"=> "Câncer",
                "mae"=> "Daniela Nina Luana",
                "pai"=> "Yago Matheus Benedito da Conceição",
                "email"=> "betina-daconceicao72@edwardmaluf.com.br",
                "senha"=> "QLaDyqmr6F",
                "cep"=> 64039568,
                "endereco"=> "Rua Altamira",
                "numero"=> 382,
                "bairro"=> "Esplanada",
                "cidade"=> "Teresina",
                "estado"=> "PI",
                "telefone_fixo"=> "(86) 2692-0397",
                "celular"=> "(86) 99660-7425",
                "altura"=> "1,80",
                "peso"=> 67,
                "tipo_sanguineo"=> "O+",
                "cor"=> "azul"
            ],
            [
                "nome"=> "Mateus Filipe Oliver Nunes",
                "idade"=> 48,
                "cpf"=> "862.684.994-09",
                "rg"=> "22.230.688-9",
                "data_nasc"=> "01/11/1975",
                "sexo"=> "Masculino",
                "signo"=> "Escorpião",
                "mae"=> "Sabrina Carla Lara",
                "pai"=> "Samuel Joaquim Nunes",
                "email"=> "mateus_nunes@quarttus.com.br",
                "senha"=> "3eyJ5XPWhs",
                "cep"=> 29046685,
                "endereco"=> "Rua Léa",
                "numero"=> 792,
                "bairro"=> "Santa Martha",
                "cidade"=> "Vitória",
                "estado"=> "ES",
                "telefone_fixo"=> "(27) 2855-5557",
                "celular"=> "(27) 99490-8256",
                "altura"=> "1,68",
                "peso"=> 109,
                "tipo_sanguineo"=> "B+",
                "cor"=> "azul"
            ],
            [
                "nome"=> "Carolina Vitória Jesus",
                "idade"=> 51,
                "cpf"=> "304.284.494-33",
                "rg"=> "48.260.638-1",
                "data_nasc"=> "23/06/1972",
                "sexo"=> "Feminino",
                "signo"=> "Câncer",
                "mae"=> "Helena Bárbara Andreia",
                "pai"=> "Breno Kevin Jesus",
                "email"=> "carolina_jesus@inovasom.com",
                "senha"=> "NKTahwTTGJ",
                "cep"=> 27345220,
                "endereco"=> "Avenida Verbo Divino",
                "numero"=> 581,
                "bairro"=> "Verbo Divino",
                "cidade"=> "Barra Mansa",
                "estado"=> "RJ",
                "telefone_fixo"=> "(24) 2748-5901",
                "celular"=> "(24) 98698-6792",
                "altura"=> "1,62",
                "peso"=> 84,
                "tipo_sanguineo"=> "AB-",
                "cor"=> "vermelho"
            ],
            [
                "nome"=> "Nathan Danilo Heitor Peixoto",
                "idade"=> 46,
                "cpf"=> "826.666.997-06",
                "rg"=> "36.479.208-5",
                "data_nasc"=> "19/02/1977",
                "sexo"=> "Masculino",
                "signo"=> "Aquário",
                "mae"=> "Andrea Kamilly",
                "pai"=> "Renato Renan Peixoto",
                "email"=> "nathan-peixoto84@officetectecnologia.com.br",
                "senha"=> "E7oeLaj3zP",
                "cep"=> 57017692,
                "endereco"=> "Rua Faustino Silveira",
                "numero"=> 117,
                "bairro"=> "Bebedouro",
                "cidade"=> "Maceió",
                "estado"=> "AL",
                "telefone_fixo"=> "(82) 3913-8381",
                "celular"=> "(82) 99718-9623",
                "altura"=> "1,69",
                "peso"=> 80,
                "tipo_sanguineo"=> "AB+",
                "cor"=> "vermelho"
            ],
            [
                "nome"=> "Enzo Miguel Castro",
                "idade"=> 23,
                "cpf"=> "310.350.907-32",
                "rg"=> "48.017.366-7",
                "data_nasc"=> "05/06/2000",
                "sexo"=> "Masculino",
                "signo"=> "Gêmeos",
                "mae"=> "Carolina Julia",
                "pai"=> "Benício Tiago Castro",
                "email"=> "enzo-castro80@newpark.com",
                "senha"=> "3NJLNBfRik",
                "cep"=> 64215130,
                "endereco"=> "Rua Francisco Severiano",
                "numero"=> 658,
                "bairro"=> "São Francisco da Guarita",
                "cidade"=> "Parnaíba",
                "estado"=> "PI",
                "telefone_fixo"=> "(86) 2797-6248",
                "celular"=> "(86) 98964-3377",
                "altura"=> "1,68",
                "peso"=> 75,
                "tipo_sanguineo"=> "B+",
                "cor"=> "amarelo"
            ]
            ];
            $mensagens = [
                ["mensagem"=>"Olá, tudo bem?", "data"=>"2023-11-08 10:00:00"],
                ["mensagem"=>"Como você está?", "data"=>"2023-11-08 10:05:00"],
                ["mensagem"=>"Tudo tranquilo por aí?", "data"=>"2023-11-08 10:10:00"],
                ["mensagem"=>"O que você tem feito de bom?", "data"=>"2023-11-08 10:15:00"],
                ["mensagem"=>"Estou ótimo, obrigado!", "data"=>"2023-11-08 10:20:00"],
                ["mensagem"=>"E você?", "data"=>"2023-11-08 10:25:00"],
                ["mensagem"=>"Tenha um bom dia!", "data"=>"2023-11-08 10:30:00"],
                ["mensagem"=>"Como foi seu fim de semana?", "data"=>"2023-11-08 10:35:00"],
                ["mensagem"=>"Espero que tenha sido divertido!", "data"=>"2023-11-08 10:40:00"],
                ["mensagem"=>"Estou ansioso para ouvir suas novidades.", "data"=>"2023-11-08 10:45:00"],
                ["mensagem"=>"Oi! Como estão as coisas?", "data"=>"2023-11-08 10:50:00"],
                ["mensagem"=>"Alguma novidade emocionante?", "data"=>"2023-11-08 10:55:00"],
                ["mensagem"=>"Estou ansioso para o nosso próximo encontro.", "data"=>"2023-11-08 11:00:00"],
                ["mensagem"=>"Olá, amigo!", "data"=>"2023-11-08 11:05:00"],
                ["mensagem"=>"Espero que seu dia esteja indo bem.", "data"=>"2023-11-08 11:10:00"],
                ["mensagem"=>"Você fez algum progresso em seu projeto?", "data"=>"2023-11-08 11:15:00"],
                ["mensagem"=>"Mal posso esperar para ver o que você fez.", "data"=>"2023-11-08 11:20:00"],
                ["mensagem"=>"Tenha um dia maravilhoso!", "data"=>"2023-11-08 11:25:00"],
                ["mensagem"=>"Como foi o seu fim de semana?", "data"=>"2023-11-08 11:30:00"],
                ["mensagem"=>"Alguma aventura interessante?", "data"=>"2023-11-08 11:35:00"],
                ["mensagem"=>"Estou curioso para saber.", "data"=>"2023-11-08 11:40:00"],
                ["mensagem"=>"Oi, como você está?", "data"=>"2023-11-08 11:45:00"],
                ["mensagem"=>"Espero que esteja tudo bem.", "data"=>"2023-11-08 11:50:00"],
                ["mensagem"=>"Você fez algum plano para o futuro?", "data"=>"2023-11-08 11:55:00"],
                ["mensagem"=>"Olá, como estão as coisas?", "data"=>"2023-11-08 12:00:00"],
                ["mensagem"=>"Espero que seu dia esteja indo bem.", "data"=>"2023-11-08 12:05:00"],
                ["mensagem"=>"Você fez algo interessante recentemente?", "data"=>"2023-11-08 12:10:00"],
                ["mensagem"=>"Tenha um ótimo dia!", "data"=>"2023-11-08 12:15:00"],
                ["mensagem"=>"Como foi sua semana?", "data"=>"2023-11-08 12:20:00"],
                ["mensagem"=>"Alguma novidade para compartilhar?", "data"=>"2023-11-08 12:25:00"],
                ["mensagem"=>"Estou ansioso para ouvir!", "data"=>"2023-11-08 12:30:00"],
                ["mensagem"=>"Oi! Como está?", "data"=>"2023-11-08 12:35:00"],
                ["mensagem"=>"Espero que esteja tudo bem.", "data"=>"2023-11-08 12:40:00"],
                ["mensagem"=>"O que você tem feito ultimamente?", "data"=>"2023-11-08 12:45:00"],
                ["mensagem"=>"Tenha um dia incrível!", "data"=>"2023-11-08 12:50:00"],
                ["mensagem"=>"Como estão as coisas por aí?", "data"=>"2023-11-08 12:55:00"],
                ["mensagem"=>"Alguma novidade emocionante?", "data"=>"2023-11-08 13:00:00"],
                ["mensagem"=>"Mal posso esperar para ouvir!", "data"=>"2023-11-08 13:05:00"],
                ["mensagem"=>"Oi, meu amigo!", "data"=>"2023-11-08 13:10:00"],
                ["mensagem"=>"Como tem sido seu dia?", "data"=>"2023-11-08 13:15:00"],
                ["mensagem"=>"Alguma descoberta interessante?", "data"=>"2023-11-08 13:20:00"],
                ["mensagem"=>"Estou curioso para saber!", "data"=>"2023-11-08 13:25:00"],
                ["mensagem"=>"Olá, como você está?", "data"=>"2023-11-08 13:30:00"],
                ["mensagem"=>"Espero que tudo esteja indo bem.", "data"=>"2023-11-08 13:35:00"],
                ["mensagem"=>"Você fez algum progresso recentemente?", "data"=>"2023-11-08 13:40:00"],
                ["mensagem"=>"Tenha um ótimo dia!", "data"=>"2023-11-08 13:45:00"],
                ["mensagem"=>"Como foi seu fim de semana?", "data"=>"2023-11-08 13:50:00"],
                ["mensagem"=>"Alguma aventura interessante?", "data"=>"2023-11-08 13:55:00"],
                ["mensagem"=>"Estou curioso para saber!", "data"=>"2023-11-08 14:00:00"],
                ["mensagem"=>"Oi, como estão as coisas?", "data"=>"2023-11-08 14:05:00"],
                ["mensagem"=>"Espero que esteja tudo bem.", "data"=>"2023-11-08 14:10:00"],
                ["mensagem"=>"Você fez algum plano para o futuro?", "data"=>"2023-11-08 14:15:00"],
                ["mensagem"=>"Olá, como você está?", "data"=>"2023-11-08 14:20:00"],
                ["mensagem"=>"Espero que seu dia esteja indo bem.", "data"=>"2023-11-08 14:25:00"],
                ["mensagem"=>"Você fez algo interessante recentemente?", "data"=>"2023-11-08 14:30:00"],
                ["mensagem"=>"Tenha um ótimo dia!", "data"=>"2023-11-08 14:35:00"],
                ["mensagem"=>"Como foi sua semana?", "data"=>"2023-11-08 14:40:00"],
                ["mensagem"=>"Alguma novidade para compartilhar?", "data"=>"2023-11-08 14:45:00"],
                ["mensagem"=>"Estou ansioso para ouvir!", "data"=>"2023-11-08 14:50:00"],
                ["mensagem"=>"Oi! Como está?", "data"=>"2023-11-08 14:55:00"],
                ["mensagem"=>"Espero que esteja tudo bem.", "data"=>"2023-11-08 15:00:00"],
                ["mensagem"=>"O que você tem feito ultimamente?", "data"=>"2023-11-08 15:05:00"],
                ["mensagem"=>"Tenha um dia incrível!", "data"=>"2023-11-08 15:10:00"],
                ["mensagem"=>"Como estão as coisas por aí?", "data"=>"2023-11-08 15:15:00"],
                ["mensagem"=>"Alguma novidade emocionante?", "data"=>"2023-11-08 15:20:00"],
                ["mensagem"=>"Mal posso esperar para ouvir!", "data"=>"2023-11-08 15:25:00"],
                ["mensagem"=>"Oi, meu amigo!", "data"=>"2023-11-08 15:30:00"],
                ["mensagem"=>"Como tem sido seu dia?", "data"=>"2023-11-08 15:35:00"],
                ["mensagem"=>"Alguma descoberta interessante?", "data"=>"2023-11-08 15:40:00"],
                ["mensagem"=>"Estou curioso para saber!", "data"=>"2023-11-08 15:45:00"],
                ["mensagem"=>"Olá, como você está?", "data"=>"2023-11-08 15:50:00"],
                ["mensagem"=>"Espero que tudo esteja indo bem.", "data"=>"2023-11-08 15:55:00"],
                ["mensagem"=>"Você fez algum progresso recentemente?", "data"=>"2023-11-08 16:00:00"],
                ["mensagem"=>"Tenha um ótimo dia!", "data"=>"2023-11-08 16:05:00"],
                ["mensagem"=>"Como foi seu fim de semana?", "data"=>"2023-11-08 16:10:00"],
                ["mensagem"=>"Alguma aventura interessante?", "data"=>"2023-11-08 16:15:00"],
                ["mensagem"=>"Estou curioso para saber!", "data"=>"2023-11-08 16:20:00"],
                ["mensagem"=>"Oi, como estão as coisas?", "data"=>"2023-11-08 16:25:00"],
                ["mensagem"=>"Espero que esteja tudo bem.", "data"=>"2023-11-08 16:30:00"],
                ["mensagem"=>"Você fez algum plano para o futuro?", "data"=>"2023-11-08 16:35:00"],
                ["mensagem"=>"Olá, como você está?", "data"=>"2023-11-08 16:40:00"],
                ["mensagem"=>"Espero que seu dia esteja indo bem.", "data"=>"2023-11-08 16:45:00"],
                ["mensagem"=>"Você fez algo interessante recentemente?", "data"=>"2023-11-08 16:50:00"],
                ["mensagem"=>"Tenha um ótimo dia!", "data"=>"2023-11-08 16:55:00"],
                ["mensagem"=>"Como foi sua semana?", "data"=>"2023-11-08 17:00:00"],
                ["mensagem"=>"Alguma novidade para compartilhar?", "data"=>"2023-11-08 17:05:00"],
                ["mensagem"=>"Estou ansioso para ouvir!", "data"=>"2023-11-08 17:10:00"],
                ["mensagem"=>"Oi! Como está?", "data"=>"2023-11-08 17:15:00"],
                ["mensagem"=>"Espero que esteja tudo bem.", "data"=>"2023-11-08 17:20:00"],
                ["mensagem"=>"O que você tem feito ultimamente?", "data"=>"2023-11-08 17:25:00"],
                ["mensagem"=>"Tenha um dia incrível!", "data"=>"2023-11-08 17:30:00"],
                ["mensagem"=>"Como estão as coisas por aí?", "data"=>"2023-11-08 17:35:00"],
                ["mensagem"=>"Alguma novidade emocionante?", "data"=>"2023-11-08 17:40:00"],
                ["mensagem"=>"Mal posso esperar para ouvir!", "data"=>"2023-11-08 17:45:00"],
                ["mensagem"=>"Oi, meu amigo!", "data"=>"2023-11-08 17:50:00"],
                ["mensagem"=>"Como tem sido seu dia?", "data"=>"2023-11-08 17:55:00"],
                ["mensagem"=>"Alguma descoberta interessante?", "data"=>"2023-11-08 18:00:00"],
                ["mensagem"=>"Estou curioso para saber!", "data"=>"2023-11-08 18:05:00"],
                ["mensagem"=>"Olá, como você está?", "data"=>"2023-11-08 18:10:00"],
                ["mensagem"=>"Espero que tudo esteja indo bem.", "data"=>"2023-11-08 18:15:00"]
            ];


            foreach($rows as $row){
                $this->insert('pessoas', ['name'=>$row['nome'], 'email'=>$row['email']]);
                $idP = $this->db->getLastInsertID();
                $this->insert('address', ['country'=>'BR', 'uf'=>$row['estado'], 'city'=>$row['cidade'], 'district'=>$row['bairro'], 'street'=>$row['endereco'], 'number'=>$row['numero'], 'CEP'=>$row['cep'], 'pessoas_id'=>$idP]);
                $this->insert('chats',[]);
                $idC = $this->db->getLastInsertID();
                foreach($mensagens as $mensagen){
                    $this->insert('mensagens',['mensagem'=>$mensagen['mensagem'], 'data'=>$mensagen['data'], 'pessoa_id'=>$idP, 'chat_id'=>$idC]);
                }
            }

            
        }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->delete('address');
        $this->delete('mensagens');
        $this->delete('pessoas');
        $this->delete('chats');
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m231102_180814_add_rows cannot be reverted.\n";

        return false;
    }
    */
}
