<?php

return [
    [
        "uf" => "PR",
        "localidade" => "Londrina",
        "bairro" => "Jardim do Sol",
        "cep" => "86070370",
    ],
    [
        "uf" => "PR",
        "localidade" => "Londrina",
        "bairro" => "Lindóia",
        "cep" => "86031770",
    ],
    [
        "uf" => "PR",
        "localidade" => "Londrina",
        "bairro" => "Estância Santa Paula",
        "cep" => "86058467",
    ],
    [
        "uf" => "PR",
        "localidade" => "Londrina",
        "bairro" => "Cilo 3",
        "cep" => "86073040",
    ],
    [
        "uf" => "PR",
        "localidade" => "Londrina",
        "bairro" => "Jardim Morumbi",
        "cep" => "86036370",
    ],
    [
        "uf" => "PR",
        "localidade" => "Londrina",
        "bairro" => "São Pedro",
        "cep" => "86036300",
    ],
    [
        "uf" => "PR",
        "localidade" => "Londrina",
        "bairro" => "Jardim Shangri-la A",
        "cep" => "86070440",
    ],
    [
        "uf" => "PR",
        "localidade" => "Curitiba",
        "bairro" => "Guaíra",
        "cep" => "80630275",
    ],
    [
        "uf" => "PR",
        "localidade" => "Curitiba",
        "bairro" => "Cabral",
        "cep" => "80035130",
    ],
    [
        "uf" => "PR",
        "localidade" => "Curitiba",
        "bairro" => "Tatuquara",
        "cep" => "81470208",
    ],
    [
        "uf" => "PR",
        "localidade" => "Curitiba",
        "bairro" => "Portão",
        "cep" => "80610260",
    ],
    [
        "uf" => "PR",
        "localidade" => "Curitiba",
        "bairro" => "Portão",
        "cep" => "80610265",
    ],
    [
        "uf" => "SP",
        "localidade" => "São Paulo",
        "bairro" => "Jardim Paulista",
        "cep" => "01424007",
    ],
    [
        "uf" => "SP",
        "localidade" => "São Paulo",
        "bairro" => "Jardim Paulista",
        "cep" => "01424003",
    ],
    [
        "uf" => "SP",
        "localidade" => "São Paulo",
        "bairro" => "Jardim Paulista",
        "cep" => "01424002",
    ],
    [
        "uf" => "SP",
        "localidade" => "São Paulo",
        "bairro" => "Jardim Paulista",
        "cep" => "01424005",
    ],
    [
        "uf" => "SP",
        "localidade" => "São Paulo",
        "bairro" => "Jardim Paulista",
        "cep" => "01424004",
    ],
    [
        "uf" => "SP",
        "localidade" => "São Paulo",
        "bairro" => "Cerqueira César",
        "cep" => "01418000",
    ],
    [
        "uf" => "SP",
        "localidade" => "São Paulo",
        "bairro" => "Cerqueira César",
        "cep" => "01419000",
    ],
    [
        "uf" => "SP",
        "localidade" => "São Paulo",
        "bairro" => "Cerqueira César",
        "cep" => "01419002",
    ],
    [
        "uf" => "SP",
        "localidade" => "São Paulo",
        "bairro" => "Cerqueira César",
        "cep" => "01418100",
    ],
    [
        "uf" => "SP",
        "localidade" => "São Paulo",
        "bairro" => "Cerqueira César",
        "cep" => "01419100",
    ],
    [
        "uf" => "SP",
        "localidade" => "São Paulo",
        "bairro" => "Cerqueira César",
        "cep" => "01418102",
    ]
    ,[
        "uf" => "SP",
        "localidade" => "Campinas",
        "bairro" => "Nova Campinas",
        "cep" => "13092112",
    ],
    [
        "uf" => "SP",
        "localidade" => "Campinas",
        "bairro" => "Cidade Universitária",
        "cep" => "13083897",
    ],
    [
        "uf" => "SP",
        "localidade" => "Campinas",
        "bairro" => "Nova Campinas",
        "cep" => "13092132",
    ],
    [
        "uf" => "SP",
        "localidade" => "Campinas",
        "bairro" => "Cidade Universitária",
        "cep" => "13083851",
    ],
    [
        "uf" => "SP",
        "localidade" => "Campinas",
        "bairro" => "Jardim Nilópolis",
        "cep" => "13088851",
    ],
    [
        "uf" => "SP",
        "localidade" => "Campinas",
        "bairro" => "Loteamento Chácaras Gargantilhas",
        "cep" => "13098864",
    ],
    [
        "uf" => "SP",
        "localidade" => "Campinas",
        "bairro" => "Jardim Independência",
        "cep" => "13084472",
    ],
    [
        "uf" => "RJ",
        "localidade" => "Rio de Janeiro",
        "bairro" => "Tomás Coelho",
        "cep" => "20761372",
    ],
    [
        "uf" => "RJ",
        "localidade" => "Rio de Janeiro",
        "bairro" => "Tomás Coelho",
        "cep" => "20761371",
    ],
    [
        "uf" => "RJ",
        "localidade" => "Niterói",
        "bairro" => "Pendotiba",
        "cep" => "24322020",
    ],
    [
        "uf" => "RJ",
        "localidade" => "Niterói",
        "bairro" => "Icaraí",
        "cep" => "24230270",
    ],
    [
        "uf" => "RJ",
        "localidade" => "Niterói",
        "bairro" => "Piratininga",
        "cep" => "24350730",
    ],
    [
        "uf" => "RJ",
        "localidade" => "Niterói",
        "bairro" => "Jurujuba",
        "cep" => "24370195",
    ],
    [
        "uf" => "RJ",
        "localidade" => "Niterói",
        "bairro" => "Piratininga",
        "cep" => "24350031",
    ],
    [
        "uf" => "RJ",
        "localidade" => "Niterói",
        "bairro" => "Piratininga",
        "cep" => "24358253",
    ],
    [
        "uf" => "RJ",
        "localidade" => "Niterói",
        "bairro" => "Itaipu",
        "cep" => "24340105",
    ],
    [
        "uf" => "RJ",
        "localidade" => "Niterói",
        "bairro" => "Maravista",
        "cep" => "24340100",
    ],
    [
        "uf" => "RJ",
        "localidade" => "Niterói",
        "bairro" => "Rio do Ouro",
        "cep" => "24330280",
    ],
    [
        "uf" => "RJ",
        "localidade" => "Niterói",
        "bairro" => "Várzea das Moças",
        "cep" => "24330285",
    ],
    [
        "uf" => "RJ",
        "localidade" => "Niterói",
        "bairro" => "Centro",
        "cep" => "24020020",
    ]
    ,[
        "uf" => "DF",
        "localidade" => "Brasília",
        "bairro" => "Santa Maria",
        "cep" => "72510246",
    ],
    [
        "uf" => "DF",
        "localidade" => "Brasília",
        "bairro" => "Setor Oeste (Gama)",
        "cep" => "72425015",
    ],
    [
        "uf" => "DF",
        "localidade" => "Brasília",
        "bairro" => "Setor Oeste (Gama)",
        "cep" => "72425048",
    ],
    [
        "uf" => "DF",
        "localidade" => "Brasília",
        "bairro" => "Setor Oeste (Gama)",
        "cep" => "72425055",
    ],
    [
        "uf" => "DF",
        "localidade" => "Brasília",
        "bairro" => "Setor Oeste (Gama)",
        "cep" => "72425053",
    ],
    [
        "uf" => "DF",
        "localidade" => "Brasília",
        "bairro" => "Setor Oeste (Gama)",
        "cep" => "72425054",
    ],
    [
        "uf" => "DF",
        "localidade" => "Brasília",
        "bairro" => "Setor Oeste (Gama)",
        "cep" => "72425056",
    ],
    [
        "uf" => "DF",
        "localidade" => "Brasília",
        "bairro" => "Setor Oeste (Gama)",
        "cep" => "72425057",
    ],
    [
        "uf" => "DF",
        "localidade" => "Brasília",
        "bairro" => "Setor Oeste (Gama)",
        "cep" => "72425058",
    ],
    [
        "uf" => "DF",
        "localidade" => "Brasília",
        "bairro" => "Samambaia Norte (Samambaia)",
        "cep" => "72322615",
    ],
    [
        "uf" => "DF",
        "localidade" => "Brasília",
        "bairro" => "Setor Norte (Brazlândia)",
        "cep" => "72710067",
    ],
    [
        "uf" => "DF",
        "localidade" => "Brasília",
        "bairro" => "Setor Oeste (Gama)",
        "cep" => "72425095",
    ],
    [
        "uf" => "DF",
        "localidade" => "Brasília",
        "bairro" => "Setor Oeste (Gama)",
        "cep" => "72425097",
    ] 
    ];